# Generated by Django 4.2.5 on 2023-09-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='quantity_product',
        ),
        migrations.AlterField(
            model_name='product',
            name='date_create',
            field=models.DateField(verbose_name='дата создания'),
        ),
    ]
