# Generated by Django 4.2.5 on 2023-09-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_quantity_product_quantity_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='product',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='просмотры'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_create',
            field=models.DateField(default='18/09/2023', verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_product',
            field=models.IntegerField(default=0, verbose_name='количество'),
        ),
    ]
